### ISSUE TITLE
Failed to install in VS 2019

### ISSUE THREAD

**Issue by glittle** [loop8ack/ExtensionPackTools#6]
When installing, choose to install to VS 2017 and VS 2019 Preview.  The install to VS 2017 worked.  The one for 2019 failed.

Here's the last line of the install log file.  I have the complete file, if that would help.

2018-12-13 4:45:21 PM - Install Error : Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.DiagnosticsHub.Collection.Service' failed to install
   at Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   at Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   at Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by Thieum** [comment]
In Visual Studio 2019 Preview 2.2, I get the same exception:

```
2019-02-06 09:08:58 - Erreur d'installation : System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.DiagnosticsHub.Collection.Service' failed to install
   à Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   à Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   à Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   à Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   à Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   à System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   à Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install()
   à Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   à Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
---> (Exception interne #0) Microsoft.VisualStudio.Setup.PackageFailureException: Package 'Microsoft.DiagnosticsHub.Collection.Service' failed to install
   à Microsoft.VisualStudio.Setup.InstallOperation.Run(CancellationToken token)
   à Microsoft.VisualStudio.Setup.Engine.RunOperation(InstallOperation installOperation, CancellationToken token, ExecuteAction action, ITelemetryOperation telemetryOperation)
   à Microsoft.VisualStudio.Setup.Engine.RunCoreOperation(InstallOperation coreOperation, ExecuteAction action, ITelemetryOperation telemetryOperation, CancellationToken token)
   à Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   à Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   à System.Threading.Tasks.Task`1.InnerInvoke()
   à System.Threading.Tasks.Task.Execute()<---
```
On both install and uninstall - logs here:
[install_dd_VSIXInstaller_20190206090745.log](https://github.com/madskristensen/ExtensionPackTools/files/2836625/install_dd_VSIXInstaller_20190206090745.log)
[Uninstall_dd_VSIXInstaller_20190206090515.log](https://github.com/madskristensen/ExtensionPackTools/files/2836626/Uninstall_dd_VSIXInstaller_20190206090515.log)

But it doesn't prevent the extension to be installed.
![image](https://user-images.githubusercontent.com/944894/52347338-ab566800-29ef-11e9-98c8-3825400fae24.png)

**Comment by schuettecarsten** [comment]
I get an error message when VS2019 opens a solution:

```
  <entry>
    <record>4886</record>
    <time>2019/02/13 22:45:15.811</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [VsPackage]Source: &apos;ExtensionManager&apos; Description: Die Datei oder Assembly &quot;Microsoft.VisualStudio.ExtensionManager, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;System.IO.FileNotFoundException: Die Datei oder Assembly &quot;Microsoft.VisualStudio.ExtensionManager, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&quot; oder eine Abh&#x00E4;ngigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.&#x000D;&#x000A;File name: &apos;Microsoft.VisualStudio.ExtensionManager, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos;&#x000D;&#x000A;   at ExtensionManager.VsPackage.&lt;InitializeAsync&gt;d__0.MoveNext()&#x000D;&#x000A;   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine&amp; stateMachine)&#x000D;&#x000A;   at ExtensionManager.VsPackage.InitializeAsync(CancellationToken cancellationToken, IProgress`1 progress)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass19_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Threading.JoinableTask.&lt;JoinAsync&gt;d__68.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()&#x000D;&#x000A;&#x000D;&#x000A;WRN: Protokollierung der Assemblybindung ist AUS.&#x000D;&#x000A;Sie k&#x00F6;nnen die Protokollierung der Assemblybindungsfehler aktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) auf 1 festlegen.&#x000D;&#x000A;Hinweis: Die Protokollierung der Assemblybindungsfehler f&#x00FC;hrt zu einer gewissen Leistungseinbu&#x00DF;e.&#x000D;&#x000A;Sie k&#x00F6;nnen dieses Feature deaktivieren, indem Sie den Registrierungswert [HKLM\Software\Microsoft\Fusion!EnableLog] entfernen.&#x000D;&#x000A;</description>
    <guid>{3EC2FA73-1F0D-4E31-88C3-604C4E46EC14}</guid>
    <hr>80070002</hr>
    <errorinfo></errorinfo>
  </entry>
```

**Comment by madskristensen** [comment]
That should all be fixed in the latest release
